# Path to data
# DATA_PATH: "/media/farm/2E6512C924458521/delete_excess/tape/"
# DATA_PATH: "/home/farm/PycharmProjects/train_yolo_utils/res_dir/home"
DATA_PATH: "/media/farm/ssd_1_tb_evo_sumsung/train_yolo_utils/res_dir/home"
# Path to file with class name

CLASSES: "../classes.txt"

IMG_SIZE: "832"
BATCH_SIZE: "60"
EPOCHS: "400"

# This file generated automaticaly
CONFIG_PATH: "dataset.yaml"

# Path to trainable model
#MODEL_PATH: '/home/farm/PycharmProjects/train_yolo_utils/yolov5/models/yolov5x.yaml'
MODEL_PATH: '/media/farm/ssd_1_tb_evo_sumsung/train_yolo_utils/yolov5/models/yolov5x.yaml'

SAVE_PATH: "yolov5_x_28.pt"
MODEL_NAME: "yolov5_result"